[env:ATmega328P]
platform = atmelavr
board = ATmega328P
framework = arduino

monitor_speed = 9600

lib_deps =
    adafruit/RTClib
    marcoschwartz/LiquidCrystal_I2C
    arduino-libraries/Servo

upload_protocol = custom

upload_command = avrdude -C "$PROJECT_PACKAGES_DIR/tool-avrdude/avrdude.conf" -p atmega328p -c xplainedmini -P usb -U flash:w:$SOURCE:i 